
services:
  web:
    build: .
    container_name: drf_web
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: drf_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: drf_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: