# Generated by Django 5.2.5 on 2025-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_alter_project_end_at_alter_project_start_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
