# Generated by Django 5.2.5 on 2025-10-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_alter_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archive', 'Archive')], db_index=True, default='active', max_length=10),
        ),
    ]
